# Generated by Django 5.1.5 on 2025-01-31 12:46

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CallRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('call_sid', models.CharField(max_length=255, unique=True)),
                ('call_status', models.CharField(blank=True, max_length=100, null=True)),
                ('ghl_contact_id', models.CharField(blank=True, max_length=255, null=True)),
                ('ghl_contact_fullname', models.CharField(blank=True, max_length=255, null=True)),
                ('ghl_location_id', models.CharField(blank=True, max_length=255, null=True)),
                ('call_from', models.CharField(blank=True, max_length=255, null=True)),
                ('call_to', models.CharField(blank=True, max_length=255, null=True)),
                ('call_started_at', models.DateTimeField(blank=True, null=True)),
                ('call_direction', models.CharField(blank=True, max_length=100, null=True)),
                ('call_duration', models.IntegerField(blank=True, null=True)),
                ('call_recording_url', models.URLField(blank=True, null=True)),
                ('first_time', models.BooleanField(default=False)),
                ('ghl_location_name', models.CharField(blank=True, max_length=255, null=True)),
                ('source', models.CharField(blank=True, max_length=255, null=True)),
                ('source_type', models.CharField(blank=True, max_length=255, null=True)),
                ('landing_page', models.CharField(blank=True, max_length=255, null=True)),
                ('referrer', models.CharField(blank=True, max_length=255, null=True)),
                ('campaign', models.CharField(blank=True, max_length=255, null=True)),
                ('transcript_id', models.CharField(blank=True, max_length=255, null=True)),
                ('transcription', models.TextField(blank=True, null=True)),
                ('summary', models.TextField(blank=True, null=True)),
            ],
        ),
    ]
