# Generated by Django 5.1.5 on 2025-01-31 16:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='callrecord',
            name='first_time',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
    ]
