# Generated by Django 5.1.5 on 2025-02-03 13:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_v2'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='v2',
            name='assembly_ai_id',
        ),
    ]
