# Generated by Django 5.1.5 on 2025-02-03 13:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_remove_v2_assembly_ai_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='v2',
            name='note_id',
            field=models.TextField(blank=True, null=True, unique=True),
        ),
    ]
