# Generated by Django 5.1.5 on 2025-02-03 14:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_alter_v2_note_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='v2',
            name='note_id',
            field=models.CharField(blank=True, max_length=255, null=True, unique=True),
        ),
    ]
